# trigger build
version: 2
debug: true
jobs:
  build:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run:
          name: "Build"
          command: "make all"
      - run:
          name: "Run Unit Tests"
          command: "make test-all"
workflows:
  version: 2
  build:
    jobs:
      - build
