# trigger build
version: 2
debug: true
jobs:
  build:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run: sudo apt-get install vim
      - run:
          name: "Build"
          command: "make all"
      - run:
          name: "Run Unit Tests"
          command: "make test-all"
      - run:
          name: "Generate Reports"
          command: "make cov-all"
      - run:
          name: "Upload Reports"
          command: "bash < (curl -s https://codecov.io/bash)"
workflows:
  version: 2
  build:
    jobs:
      - build
